/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */
buildscript {
    repositories {
        mavenLocal()
    }

    dependencies {
        classpath("bilibili:poc:1.0")
    }
}

plugins {
    id("com.gradle.enterprise") version("3.10.1")
}

if (gradle.startParameter.taskNames.none { it.contains("publishToMavenLocal") }) {
    apply(plugin = "bilibili-poc-plugin")
}
rootProject.name = "bilibili-poc"
include("app", "monitor-plugin")
