/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */
pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}


plugins {
    if (System.getProperty("publishToMavenLocal") == null) {
        id("bilibili-poc-plugin") version ("1.0")
    }
    if (System.getProperty("noGradleEnterprise") == null) {
        id("com.gradle.enterprise") version ("3.10.1")
    }
}

rootProject.name = "bilibili-poc"
include("monitor-plugin")
