/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
//    id("bilibili.poc.java-application-conventions")
}

dependencies {
//    implementation("org.apache.commons:commons-text")
//    implementation(project(":utilities"))
}

//application {
    // Define the main class for the application.
//    mainClass.set("bilibili.poc.app.App")
//}
